load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "data",
    srcs = [
        "cli_input.go",
        "constants.go",
    ],
    importpath = "shell_history_client/data",
    visibility = ["//visibility:public"],
)
