load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cmd",
    srcs = ["create.go"],
    importpath = "shell_history_client/cmd",
    visibility = ["//visibility:public"],
    deps = ["//data"],
)
